/*
 (c) Skimlinks 2009-2022
 Build time: Tue, 15 Mar 2022 10:51:17 GMT
 Version: "15.2.4-stackpath"
*/
(function(){function mc(){var a=r.linksImpressions;a={phr:a.skimwords.urls,unl:a.unlinked.urls,slc:a.skimlinks.count,swc:a.skimwords.count,ulc:a.unlinked.count,jsl:(new Date).getTime()-r.loading_started,pref:k.referrer,uc:ja,t:1,jsf:"",jv:V};ka&&(a.xrf=1);return fb(a)}function gb(a,b){b=b||hb(a);if(!b)return!0;ib(b);var c=g("skimlinks_keywee_pixel",null);var d=m(l.location.href,"utm_campaign=fbkw");c&&d&&jb(c);g("vglnk")&&la(b,"skimwords-link")&&(a&&a.stopPropagation?a.stopPropagation():(c=l.event,
c.cancelBubble=!0));return!0}function ib(a,b){a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=kb(a));if(a){var c=nc(a);var d=n.waypointDomain;if(c.length>=d.length&&c.substr(0,d.length)===d)return!0;if(-1!==c.indexOf(d))d=c;else{d=a;var e=la(d,"skimwords-link"),h=y(d,"data-skim-creative"),W=y(d,"data-skimlinks-tracking")||ja,g=Ga?"&"+Ga:"";c=u(ma(),{id:Ha,isjs:1,jv:V,sref:l.location,url:c,xs:1,xtz:lb(),xuuid:k.uuid});h&&(c.xcreo=h);k.isAdblockUser&&(c.abp=1);k.cookie&&
(c.xguid=k.cookie);J&&(c.site=J);W&&(c.xcust=W);e&&(c.xs=2,c.xword=y(d,"data-skimwords-word")||"");e=A(d);e.icust&&(c.xjsf=e.icust);e.sourceApp&&(c.xs=e.sourceApp);e.clientClickId&&(c.cci=e.clientClickId,delete A(d).clientClickId);e.linkSwappingMatchId&&(c.ls=e.linkSwappingMatchId);d=n.waypointDomain+"/?"+K(c)+g}mb(a,d,b)}return!0}function kb(a){for(;a.parentNode;){a=a.parentNode;var b=a.nodeName.toUpperCase();if("A"===b||"AREA"===b)return a}return null}function nb(a,b,c){a=L(l,["skimlinks_settings",
a],l[a]);return z(a)?b:q(c)?c(a,b):a}function g(a,b,c){if(M(a)){a:{void 0===a&&(a=[]);for(var d=0;d<a.length;d++){var e=nb(a[d]);if(!z(e)){if(q(c)){b=c(e,b);break a}b=e;break a}}}return b}return nb(a,b,c)}function ob(){return L(na(),["runTimeInfo","isAdblockUser"])}function X(a){try{var b=a.skimlinksOriginalHref||a.href;return oa(pb(b)?b.baseVal:b)}catch(c){return console.error("Unexpected href format"),console.error(c),""}}function qb(a){var b=document.createElement("a"),c={};b.href=a;if(a=b.search.substring(1))for(a=
a.replace(/&amp;/g,"&").split("&"),b=0;b<a.length;b++){var d=a[b].split("="),e=d[1];c[d[0]]=e?decodeURIComponent(e):null}return c}function pa(a){return a?a.replace(/^www\./i,""):""}function Ia(){for(var a="",b=0;8>b;b++)a+=Math.floor(65536*(1+Math.random())).toString(16).substring(1);return a}function q(a){return"[object Function]"===Object.prototype.toString.call(a)}function F(a,b,c){for(var d=0,e=null===a?0:a.length;d<e;)c=b(c,a[d],d,a),d+=1;return c}function qa(a){return"console"in window&&q(window.console[a])?
window.console[a]:function(){}}function ra(a,b){return F(b,function(b,d){return b&&q(a[d])},!0)}function oc(){try{var a=JSON.stringify({a:1});return 1===JSON.parse(a).a}catch(b){return!1}}function v(a,b){var c=Error(b);c.name=a;rb(c,"getPrototypeOf"in Object?Object.getPrototypeOf(this):this.__proto__);Error.captureStackTrace&&Error.captureStackTrace(c,v);return c}function rb(a,b){"setPrototypeOf"in Object?Object.setPrototypeOf(a,b):a.__proto__=b}function z(a){return"undefined"===typeof a||null===
a}function M(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)}function G(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function t(a,b){if(M(a))for(var c=0;c<a.length;c++)b(a[c],c,a);else for(c in a)G(a,c)&&b(a[c],c,a)}function u(){var a=arguments[0],b=Array.prototype.slice.call(arguments,1);z(a)&&(a={});t(b,function(b){z(b)&&(b={});t(Object.keys(b),function(c){a[c]=b[c]})});return a}function Y(a,b){var c=[];t(a,function(d,e){b(d,e,a)&&c.push(d)});
return c}function sb(a){void 0===a&&(a=[]);return Y(a,function(a){return!!a})}function Ja(a,b){if(!a)return[];if(!b)return[].concat(a);var c=[];t(a,function(d,e){c.push(b(d,e,a))});return c}function oa(a){return z(a)?"":a.toString().replace(/^[\s\xA0]+|[\s\xA0]+$/g,"")}function sa(a){return"boolean"===typeof a}function H(a,b){return"undefined"===typeof a?b:a}function Ka(a,b,c){a=H(a,"");b=H(b,"");c=H(c,0);return 0===a.slice(c).indexOf(b)}function ta(a,b,c){a=H(a,"");b=H(b,"");c=H(c,0);c=c<a.length?
c|0:a.length;return a.substr(c-b.length,b.length)===b}function pb(a){var b=typeof a;return null!==a&&("object"===b||"function"===b)}function pc(a){return encodeURIComponent(a).replace(/[!'()*~]/g,function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function w(a,b){void 0===b&&(b=!0);var c=document.createElement("a");if(b)var d=a;else{d=void 0;void 0===d&&(d="http");var e="";/^https?:\/\//.test(a)||/^\/[^/]+/.test(a)||(e=/^\/\//.test(a)?d+":":d+"://");d=""+e+a}c.href=d;try{return pa(c.hostname)}catch(h){return""}}
function K(a,b){var c=[];b=b||pc;t(a,function(a,e){c.push(e+"="+b(a))});return c.join("&")}function La(a,b,c,d){function e(){if(q(d.onError)){var b=400<=f.status&&500>f.status,c=500<=f.status&&600>f.status;d.onError(new (0===f.status?qc:b?rc:c?sc:tc)(g+" "+a+" "+f.status))}}b=b||{};d=d||{};var h=d.data,W=d.headers||{},g=d.method||"GET",f=new XMLHttpRequest;d.withCredentials&&(f.withCredentials=!0);b=K(b);b.length&&(a=a+"?"+b);f.open(g,a);t(W,function(a,b){f.setRequestHeader(b,a)});f.onload=function(){if(q(c))if(200<=
f.status&&300>f.status){try{var a=JSON.parse(f.responseText)}catch($d){a=f.responseText}c(a)}else e()};f.onerror=e;f.send(h);return f}function L(a,b,c){if(!a||!b||!b.length)return c;for(var d=b.length,e=0;e<d;e++){var h=b[e];if(a&&h in a)a=a[h];else return c}return a}function na(){return window.__SKIM_JS_GLOBAL__&&q(window.__SKIM_JS_GLOBAL__.getDebugInfo)?window.__SKIM_JS_GLOBAL__.getDebugInfo():{}}function uc(a){var b=/(?::(\d+))?:(\d+)$/,c=/^([^ ]+)\s\((.*)\)$/,d={filename:a,"function":"?",lineno:null,
colno:null,in_app:!0};c.test(a)&&(a=a.match(c).slice(1),c=a[1],d["function"]=a[0],d.filename=c);b.test(d.filename)&&(c=d.filename.match(b).slice(1),a=c[0],c=c[1],a&&c?(d.lineno=parseInt(a,10),d.colno=parseInt(c,10)):!a&&c&&(d.lineno=parseInt(c,10)),d.filename=d.filename.replace(b,""));return d}function vc(a){a=a.stack.replace(a.toString(),"").replace(/^\s+at\s+/gm,"").split("\n");a=Ja(a,function(a){return oa(a)});a=sb(a);a.reverse();return Ja(a,uc)}function ua(a,b){if(a&&tb){ub.push(a);try{wc.sendError(a,
b)}catch(d){if(d===a)vb.error(a);else{var c=new xc;c.__sentryExtraData__={logger_error_message:d.message,logger_error_stack:d.stack,initial_error_message:a.message,intial_error_stack:a.stack};throw c;}}}}function B(a){return q(a)?function(){try{a.apply(this,arguments)}catch(b){ua(b)}}:a}function wb(a){var b=!1,c;return function(){if(b)return c;c=a.apply(this,arguments);b=!0;return c}}function xb(a,b){return M(a)?a:b}function y(a,b,c){3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,
c):a[b]=c);try{var d=a[b];d||(d=a.getAttribute(b));return d}catch(e){return null}}function N(a,b){var c=Array.prototype.slice.call(arguments,2),d=B(a);return window.setTimeout.apply(window,[d,b].concat(c))}function yc(a,b){function c(){"object"===typeof a.skimlinksOriginalHref?(a.href.baseVal=a.skimlinksOriginalHref.baseVal,a.href.animVal=a.skimlinksOriginalHref.animVal):a.href=a.skimlinksOriginalHref;delete a.skimlinksOriginalHostname;delete a.skimlinksOriginalHref;delete a.skimlinksRestoreSwappedLink}
b=b||yb;var d=N(c,b);a.skimlinksOriginalHostname=a.hostname;a.skimlinksOriginalHref="object"===typeof a.href?{animVal:a.href.animVal,baseVal:a.href.baseVal}:a.href;a.skimlinksRestoreSwappedLink=function(){clearTimeout(d);c()}}function mb(a,b,c){if(a){"string"===typeof a.skimlinksOriginalHref||yc(a,c);c=null;var d=a.childNodes.length&&3===a.childNodes[0].nodeType;"msie"===k.detect.browser&&d&&(c=a.innerHTML);"object"===typeof a.href?(a.href.baseVal=b,a.href.animVal=b):a.href=b;c&&c!==a.innerHTML&&
(a.innerHTML=c)}}function zb(a){var b=a.href;b=k.cookie?b.replace(/([&?])xguid=([a-fA-F0-9]{32})/,"$1xguid="+k.cookie):b.replace(/([&?]xguid=[a-fA-F0-9]{32})/,"");b!==a.href&&mb(a,b);return b}function Ab(a){a=a||document;a=a.body||a.getElementsByTagName("body")[0];if(!a)throw new Bb;return a}function jb(a,b,c){if(!C){C=document.createElement("iframe");C.id="skimlinks-pixels-iframe";try{Ab().appendChild(C)}catch(h){h instanceof Bb&&document.documentElement.appendChild(C)}var d=C;d.width=0;d.height=
0;d.style.display="none"}var e=C.contentDocument||C.contentWindow.document;d=Ab(e);d||(d=document.createElement("body"),e.appendChild(d));e=e.createElement("img");e.src=a;e.width=1;e.height=1;q(b)&&(e.onload=B(b));q(c)&&(e.onerror=B(c));d.appendChild(e)}function ma(){var a={};Ma&&(a.dnt=Ma);Cb&&(a.fdnt=1);return a}function va(a,b,c,d){var e=d||{};d=e.usePixel||!1;var h=e.useSendBeacon||!1;e=e.callback||function(){};c=u({},c,ma());h?Db(a,b,c,e):d?Eb(a,b,c,e):Na(a,b,c,e)}function Db(a,b,c,d){b=JSON.stringify(b);
return navigator.sendBeacon&&(a=Oa(a,c),navigator.sendBeacon(a,b))?(d&&d(),!0):!1}function Eb(a,b,c,d){c=u({},c);c.rnd=Math.random();b&&(c.data=JSON.stringify(b));jb(Oa(a,c),d,d)}function Na(a,b,c,d){b=JSON.stringify(b);Pa.post(Oa(a,c),{},d,{headers:{"Content-type":"text/plain"},data:b,withCredentials:!0})}function Oa(a,b){var c=K(b),d=""+zc+a;return c?d+"?"+c:d}function m(a,b){return q(a.indexOf)?-1<a.indexOf(b):!1}function D(a){var b=pa(O);return m(a,Qa)||m(a,"go.redirectingat.com")||!!b&&m(a,b)}
function Fb(a){a=w(a);return D(a)}function f(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a}function wa(){wa=Object.assign||function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(a[d]=c[d])}return a};return wa.apply(this,arguments)}function Ac(a,b){a.prototype=Object.create(b.prototype);a.prototype.constructor=a;a.__proto__=b}function P(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
return a}function Bc(a,b){if(!a)throw Error("[matchSelector] First argument needs to be an html element.");var c=window.Element.prototype;c=c.matches||c.msMatchesSelector||c.mozMatchesSelector||c.webkitMatchesSelector;if(q(c))try{return c.call(a,b)}catch(e){return!1}c=(a.document||a.ownerDocument).querySelectorAll(b);for(var d=0;c[d]&&c[d]!==a;)d+=1;return!!c[d]}function Ra(a,b){var c=Cc(a);if(!c||!M(b)||0===b.length)return!1;var d=b.map(function(a){return a+" *"}).concat(b).join(",");return Bc(c,
d)}function Cc(a){for(;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.parentNode;return a}function Gb(a,b){for(var c=0;c<a.length;c++)if(b(a[c]))return a[c]}function Q(a,b){if("function"!=typeof a||null!=b&&"function"!=typeof b)throw new TypeError("Expected a function");if(!Q.Cache)return a;var c=function e(){for(var c=arguments.length,g=Array(c),f=0;f<c;f++)g[f]=arguments[f];c=b?b.apply(this,g):g[0];f=e.cache;if(f.has(c))return f.get(c);g=a.apply(this,g);e.cache=f.set(c,g)||f;return g};c.cache=new Q.Cache;
return c}function Hb(a,b){return!!Gb(b,function(b){var c=Ka("*"),e=ta("*"),h=b.replace(/\*/g,"");return c&&e?m(a,h):c?ta(a,h):e?Ka(a,h):a===b})}function Sa(a,b){return a&&a.length&&b?"undefined"!==typeof Gb(a,b):!1}function Dc(a){return g("_merchantSettings")?Sa(Ec,function(b){return m(a,b)}):!1}function Ta(a){if(!a||!a.href)return!0;var b=X(a);(b=!Ib(b))||(b=[].concat(Fc(),Gc(),Jb),b=b.length&&Ra(a,b)?!0:Ua.length?!Ra(a,Ua):!1);return b}function Ib(a){if(!a||Dc(a))return!1;var b=n.hostname;var c=
H(void 0,!0);c=w(a,c);var d=ta(c,"."+b)||ta(b,"."+c);if(b=c!==b&&!d)a=w(a),a=xa.length?!Hb(a,xa):Hb(a,Hc()),b=!a;return b}function Ic(a){var b;if(b=Kb)null===a.offsetParent?b=!0:(b=l.getComputedStyle,b=q(b)?"hidden"===b(a).visibility:!1);if(b)return p.IGNORE;var c=X(a);b=pa(w(c));c=c?/^https?:\/\//.test(c)||/^\/\//.test(c):!1;if(c&&!Ta(a)){if(ka)return p.TRACK;if(!0===n.aff_domains[b]||G(Va,b))return p.AFFILIATE;if(D(b))return p.PRE_AFFILIATED;if(a=Wa)a=!G(n.aff_domains,b)||z(n.aff_domains[b]);return a?
p.UNKNOWN:""===k.cookie&&Lb?p.AFFILIATE:p.TRACK}return p.IGNORE}function la(a,b){if(!a||!a.className||!b)return!1;var c=a&&a.className?oa(a.className).split(/\s+/):[];return m(c,b)}function ya(a){if("string"!==typeof a.skimlinksOriginalHref)return!1;var b=A(a),c=qb(a.href);b.icust&&b.icust!==c.xjsf&&(c.xjsf=b.icust);b.sourceApp&&b.sourceApp!==c.xs&&(c.xs=b.sourceApp);b=K(c);a.href=n.waypointDomain+"?"+b;return!0}function A(a){if(!a)throw Error("getAnchorMetaData takes an anchor HTML element as an argument");
var b=L(a,[Mb]);if(!b){b={icust:null,sourceApp:null};var c=[Mb],d=b;if(a&&c&&c.length)for(var e=c.length,h=a,f=null,g=0;g<e;g++){var k=c[g];if(g===e-1){try{a[k]=d}catch(Zd){h[f]={},h[f][k]=d}break}k in a&&pb(a[k])||(a[k]={});h=a;f=k;a=a[k]}}return b}function Nb(a,b,c){b=u({},b,{domain_id:Z,publisher_id:aa,page_url:l.location.href,impression_id:k.uuid,jv:V});var d={};navigator.sendBeacon?d.useSendBeacon=!!c:d.usePixel=!!c;va("/generic_tracking/"+a,b,{},d)}function hb(a){a=a.target||a.srcElement||a.originalTarget;
if(!a)return null;var b=(a.nodeName||"").toLowerCase();return m(["a","area"],b)?a:kb(a)}function za(a){try{return a()}catch(b){}}function Jc(a){var b=g("gtag");za(function(){b("event",R,{event_category:"click",event_label:a})})}function Kc(a){var b=g("ga");za(function(){b("send","event","click",R,a)})}function Lc(a){var b=g("_gaq");za(function(){b.push(["_trackEvent","click",R,a])})}function Mc(a){var b=g("pageTracker");b._trackPageview&&za(function(){b._trackPageview("/"+R+"/"+a)})}function Nc(a,
b){return F(Object.keys(b),function(c,d){var e=a[d]===b[d];return c&&e},!0)}function Oc(a){return F(a,function(a,c){return a.concat(c)},[])}function Aa(a,b){void 0===b&&(b=!0);var c=a?"."+a:"";return Oc(I.querySelectorAll(b?"a[href]"+c+", area[href]"+c:"a[href]"+c))}function Pc(a,b){t(a,function(a){var c=m(b,a)&&!D(a);n.aff_domains[a]=c})}function Qc(a,b){return!Sa(a,function(a){return!b(a)})}function Rc(){for(var a=new E,b=arguments.length,c=Array(b),d=0;d<b;d++)c[d]=arguments[d];a.waitFor(c);return a}
function Ob(a){return F(a,function(a,c){return m(a,c)?a:a.concat(c)},[])}function Xa(a){var b=Pb[a];if(!b)throw Error("Unknown service "+a);return b}function Qb(a,b){if(a){var c=[].concat(a.split(" "),b);c=Ob(c)}else c=b;return c}function Sc(){if(Ya||Ba){var a=[];Ya&&a.push("nofollow");Ba&&(a=Qb(Ba,a));t(Aa(),function(b){var c=a,d=y(b,"rel"),e=pa(b.hostname);e&&!0===n.aff_domains[e]&&y(b,"rel",Qb(d,c).join(" "))})}}function Tc(a){if(a.affiliationType===p.IGNORE)return!1;var b=a.anchor,c=a.affiliationType,
d=a.nativeEvent;if(a.type===S.LEFT_CLICK)if(b=a.anchor,c=a.affiliationType,c===p.AFFILIATE||c===p.UNKNOWN){b=a.anchor;c=a.nativeEvent;d=a.clientClickId;var e,h,f;if(f=g("skimlinks_strip_attribute",!1))for(h in f)if(G(f,h)){var n=f[h];(e=y(b,h))&&0===e.indexOf(n)&&(e=e.substr(n.length),y(b,h,e))}ba&&y(b,"target",ba);A(a.anchor);A(b).clientClickId=d;ya(b);R&&(a=b.href,g("gtag")?Jc(a):g("ga")?Kc(a):g("_gaq")?Lc(a):g("pageTracker")&&Mc(a));a=Rb?(a=y(b,"onclick"))&&m(a.toString(),"return false")?!0:(a=
b.onclick)&&q(a)&&m(a.toString(),".preventDefault()")?!0:!1:!1;a?(gb(c,b),(ba?l.open(b.href,ba):l.open(b.href,"_blank")).focus()):gb(c,b)}else c===p.PRE_AFFILIATED?zb(b):c===p.TRACK&&(a={publisher_id:aa,publisher_domain_id:Z,referrer:l.location.toString(),pref:k.referrer,site:""+J,url:b.href,custom:y(b,"data-skimlinks-tracking")||ja||"",xtz:k.timezone,uuid:k.uuid,product:"1"},ka&&(a.xrf=1),va("/naclicks",a,null,{usePixel:!0}));else{try{if(f=A(b),!f.icust||-1!==f.icust.indexOf("other_click__")){e=
"other_click__"+d.type+" ["+(void 0!=d.button?d.button:"")+"]";if(32<String(e).length)throw Error(e+" is not a valid icust value. The value should be less than 33 chars");A(b).icust=e;ya(b)}}catch(Yd){}c===p.AFFILIATE||c===p.UNKNOWN?ib(b,200):c===p.PRE_AFFILIATED&&zb(b)}return!0}function Uc(){Xa(T.ANCHOR_CLICK_INTERCEPTOR).registerInterceptor(Tc,ca.SKIMLINKS)}function Vc(){k.skimlinksEnabled&&(x.on("skim_js_start",Uc),da.whenBeaconFullyReady(Sc))}function fb(a){return u({pag:l.location.href,guid:k.cookie,
uuid:k.uuid,tz:k.timezone,publisher_id:aa,publisher_domain_id:Z},a)}function Wc(a){if(0!==r.awaitedModules.length&&(r.awaitedModules=Y(r.awaitedModules,function(b){return b!==a}),0===r.awaitedModules.length)){var b=mc();va("/page",b)}}function Xc(){return F(Aa(),function(a,b){var c=X(b),d=w(c),e;(e=!d)||(e=!(!la(b,"skimwords-link")&&!la(b,"skimlinks-unlinked")));(e=e||!Ib(c))||(e=b&&M(Ca)&&0!==Ca.length?Ra(b,Ca):!1);if(e)return a;(e=a.urls[c])||(e={count:0,ae:!0===n.aff_domains[d]||(null===n.aff_domains[d]||
void 0===n.aff_domains[d])&&Wa&&!D(d)?1:0});e.count++;a:{if(-1!==c.indexOf("#slm-")&&(d=c.split("#slm-"),2===d.length&&!isNaN(d[1])&&10*parseInt(d[1],10)===10*d[1])){d=parseInt(d[1],10);break a}d=null}d&&(e.slmcid=d);d=e;1===d.ae&&a.count++;d.slmcid&&(e=d.slmcid,m(r.campaign_ids,e)||r.campaign_ids.push(e));if(!Sb&&0===d.ae)return a;a.urls[c]=d;return a},{urls:{},count:0})}function Yc(){t(Zc,function(a){var b=l;"skimlinks_context_window"===a&&(b=window);G(b,a)&&(a={page_var:a,value:JSON.stringify(b[a])},
Nb("page_variable_tracking",a))})}function $c(){var a=wb(function(){r.linksImpressions.skimlinks=Xc();Wc("main-tracking");if(Object.keys(r.linksImpressions.skimlinks.urls).length){var a=fb({dl:r.linksImpressions.skimlinks.urls,hae:r.linksImpressions.skimlinks.count?1:0,typ:"l"});va("/link",a)}});da.whenNoRequestsPending(a);N(a,2E3)}function ad(){r.awaitedModules.push("main-tracking");k.skimwordsEnabled&&r.awaitedModules.push("skimwords");k.unlinkedEnabled&&r.awaitedModules.push("unlinked");Tb&&da.whenPostPageLoadBeaconCallCompleted($c);
if(navigator.sendBeacon&&1>1E4*Math.random()){var a={domain_id:Z,publisher_id:aa,page_url:l.location.href,impression_id:k.uuid,jv:V},b=Db("/generic_tracking/trackingMethodExperiment",u({trackingMethod:"sendBeacon"},a));Na("/generic_tracking/trackingMethodExperiment",u({trackingMethod:"xhr"},a));b||Na("/generic_tracking/trackingMethodExperiment",u({trackingMethod:"sendBeaconFailed"},a))}}function bd(){Yc()}function cd(a,b){var c={headers:{"Content-type":"application/json"},data:JSON.stringify({publisher_id:aa,
publisher_domain_id:Z,page_url:l.location.href,urls:a}),withCredentials:!0},d=ma();Pa.post(""+dd,d,b,c)}function Ub(a){var b=a.href;Fb(b)&&(a=Da.createFromUrl(a.href))&&(b=a.getTargetUrl());return b}function Vb(a,b){U||1E3<b?q(a)&&(U?Za?a(!0):a(!1):a(!1)):N(Vb,b*=2,a,b)}function Wb(){U||(ea.complete&&fa.complete&&(U=!0),U&&"0"!=ea.width&&"0"==fa.width&&(Za=!0))}function ed(a){function b(a){return a.toLowerCase().replace(/^\/\/|^https?:\/\//,"")}var c=Ja(Xb,b);return m(c,b(a))}function fd(){return{skimOptions:gd,
runTimeInfo:u({},{aff_domains:n.aff_domains},{consentState:hd},{loggedErrors:ub},k)}}function id(a,b){var c=!1,d;return function(){if(c)return d;N(function(){c=!1},b);c=!0;return d=a.apply(this,arguments)}}function jd(a,b,c,d){void 0===d&&(d=!1);if(a&&(a.nodeName||a===l))if(I.addEventListener){var e=B(c.bind(a));a.addEventListener(b,e,d)}else a.attachEvent("on"+b,function(){return 7>k.detect.version&&!l.event?(N(c.bind(a,l.event),100),!0):c.call(a,l.event)})}function Yb(a,b,c,d){void 0===b&&(b=[]);
if(a){var e=id(c,200);t(b,function(b){try{jd(a,b,e,d)}catch(W){}})}}function kd(){var a=Aa();return F(a,function(a,c){var b=Ea;var e=X(c);e=w(e);b&&D(e)&&(b=Da.createFromUrl(c.href))&&(e=b.getTargetDomain());e=(b=e)&&!Ta(c)&&!D(b);var h=G(n.aff_domains,b);e&&!h&&(a.push(b),n.aff_domains[b]=null,n.domain_data.domains.push(b));return a},[])}function Zb(a){var b=kd();return da.sendBeaconRequest(b,a)}function ld(){var a=new md;Pb[T.ANCHOR_CLICK_INTERCEPTOR]=a}function nd(){l.__SKIM_JS_GLOBAL__||(l.__SKIM_JS_GLOBAL__=
{});if(!l.__SKIM_JS_GLOBAL__.init){l.skimlinksAPI={};l.__SKIM_JS_GLOBAL__.init=!0;l.__SKIM_JS_GLOBAL__.getDebugInfo=fd;l.__SKIM_JS_GLOBAL__.bundledEntries=od;if(ed(n.hostname)||$a&&I.querySelector($a))k.skimlinksEnabled=!1,k.skimwordsEnabled=!1,k.unlinkedEnabled=!1;"msie"===k.detect.browser&&8>=k.detect.version&&(k.skimwordsEnabled=!1);try{Eb("/robots.txt",void 0,{__skimjs_preflight__please_ignore__:!0})}catch(a){ua(new pd,!0)}qd.detect(function(a){k.isAdblockUser=a});x.publish("skim_js_init");m(["interactive",
"complete"],I.readyState)?N(ha,0):(Zb(ia.PRE_PAGE_LOAD),document.addEventListener("DOMContentLoaded",ha),document.addEventListener("load",ha));ld();x.publish("skim_js_start")}}var vb={log:qa("log"),info:qa("info"),warn:qa("warn"),error:qa("error")},tb=function(){var a=!0;try{var b=[oc(),!!(window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest),ra(document,["querySelector","querySelectorAll"]),ra(Object,["keys"]),ra([],["indexOf"]),ra("",["indexOf"])];a=F(b,function(a,b){return a&&b},!0)}catch(c){a=
!1}!1===a&&vb.info("[Skimlinks] Your browser doesn't support the base features necessary to run our javascript.");return a}();v.prototype=Object.create(Error.prototype,{constructor:{value:Error,enumerable:!1,writable:!0,configurable:!0}});rb(v,Error);var Bb=v.bind(null,"DocumentBodyNotFound"),rd=v.bind(null,"PixelDropFailed");v.bind(null,"ScriptDropFailed");var tc=v.bind(null,"XhrError"),rc=v.bind(null,"XhrError4xx"),sc=v.bind(null,"XhrError5xx"),qc=v.bind(null,"XhrErrorZero"),xc=v.bind(null,"SentryLoggerError");
v.bind(null,"SendBeaconFailedError");var pd=v.bind(null,"ResolveSslCertificateError");v.bind(null,"DisclosureReadyStateTimeout");var V="15.2.4-stackpath",sd="https://r.skimresources.com/api/",Va={"t.umblr.com":{name:"z"}},Ha="58287X1607752",aa=58287,Z=1607752,zc="https://t.skimresources.com/api/v2",dd="https://ls.skimresources.com/api",Qa="go.skimresources.com",td="https://sl-sentry.skimlinks.com",$b="f648b8dfc7284fad8af093653eafd6ca",
ud="production",vd=1>1E3*Math.random(),wc={sendError:function(a,b){if(!$b)throw a;var c=b;c=(c=sa(c)?c:!1)||vd?a instanceof rd&&ob()?!1:!0:!1;if(c){c=td+"/api/46/store/";var d={sentry_version:"7",sentry_client:"raven-js/3.26.4",sentry_key:$b};var e={country:L(na(),["runTimeInfo","country"]),beacon_consent:L(na(),["runTimeInfo","consent"]),iab_consent:L(na(),["runTimeInfo","consentState","skimlinks_consent"]),is_adblock_user:ob(),is_top_frame:window.top===window};e={event_id:Ia(),project:"46",
platform:"javascript",logger:"javascript",release:V,exception:{values:[{type:a.name,value:a.message,stacktrace:{frames:vc(a)}}]},request:{headers:{"User-Agent":navigator.userAgent},url:location.href},extra:u({original_stacktrace:a.stack},a.__sentryExtraData__,e)};La(c,d,null,{method:"POST",data:JSON.stringify(e)})}}},ub=[],lb=wb(function(){return(new Date).getTimezoneOffset()}),ac=window.skimlinks_context_window||null,l=ac?window[ac]:window,I=l.document,wd={getItem:function(a){try{return JSON.parse(localStorage.getItem(a))}catch(b){return null}},
setItem:function(a,b){try{localStorage.setItem(a,JSON.stringify(b))}catch(c){}}},ab=g("noskim",!1),xd=g("noskimlinks",!1),yd=g("noskimwords",!0),zd=g("nounlinked",!0),Ad=g("skimwords_standard",false),Bd=g("skimwords_lite",false),Cd=g("skimwords_diy",false),Dd=g("skimwords_diy_filter",false),bc=!ab&&!xd,cc=!ab&&!yd,dc=!ab&&!zd,Ma=g("skimlinks_dnt",0,function(a){return a&&"0"!==a&&"false"!==
a?1:0}),Cb=g("skimlinks_nocookie",!1),bb=g("skimlinks_excluded_classes",[]),Jb=g("custom_excluded_selectors",[],xb),Ua=g("custom_included_selectors",[],xb),cb=g("skimlinks_exclude",["magazine.store","magazines.com","amazon.com"]),xa=g("skimlinks_include",[]),Kb=g("skimlinks_ignore_hidden_links",false),Ca=g("skimlinks_link_impression_exclude_selector",
[]),Ya=g("skimlinks_add_nofollow",false),Ba=g("skimlinks_custom_rel",""),ec=g("skimlinks_before_click_handler",false,function(a,b){return sa(a)?a:b}),Lb=g("skimlinks_first_party_na",!1),Tb=!g("noimpressions",!1),Sb=false,yb=g("skimlinks_replace_timeout",300,
function(a,b){var c=parseFloat(a);return isNaN(c)?b:c}),Wa=g("skimlinks_affiliate_unknown_links",true),ba=g("skimlinks_target",null),Ed=g("skimlinks_ajax_rerun",false),ka=g("skimlinks_revenue_forecast",false),Fd=g("skimlinks_noright",false),fc=g("skimlinks_url_extraction_rules",!1)||false,
Ga=g("skimlinks_extra_redir_params",[]).join("&"),ja=g(["affiliate_tracking","skimlinks_tracking"],!1),Fa=g("force_location"),J=g(["skimlinks_site","skimlinks_sitename"],!1),O=g("skimlinks_domain",""),R=g("skimlinks_google",false,function(a,b){return a?sa(a)?a?"skimout":"":oa(a):b?"skimout":""}),Xb=g("noskim_domains",[]),Gd=g("skimwords_horizontal_distance",80),Hd=g("skimwords_vertical_distance",
80),Id=false,Jd=g("skimwords_color",null),Kd=g("skimwords_weight",null),Ld=g("skimwords_decoration",null),Md=g("skimwords_style",null),Nd=g("skimwords_title",null),$a=g("no_skim_selector",""),Od=g("skimlinks_force_consent",!1),Pd=null,
Qd=false,Rb=true,db=g("link_swapping_404",!0),eb=g("link_swapping_product_match",!0),Ea=(db||eb)&&g("link_swapping",!0),gc=true,gd={SW_STANDARD:Ad,SW_LITE:Bd,SW_DIY:Cd,SW_DIY_FILTER:Dd,HAS_SKIMLINKS:bc,HAS_SKIMWORDS:cc,HAS_UNLINKED:dc,DO_NOT_TRACK:Ma,NO_COOKIE:Cb,SL_EXCLUDED_CLASSES:bb,CUSTOM_EXCLUDED_SELECTORS:Jb,CUSTOM_INCLUDED_SELECTORS:Ua,SL_EXCLUDED_DOMAINS:cb,
SL_INCLUDED_DOMAINS:xa,SL_IGNORE_HIDDEN_LINKS:Kb,SL_IMPRESSION_EXCLUDED_SELECTORS:Ca,SL_ADD_NOFOLLOW:Ya,SL_CUSTOM_REL:Ba,SL_BEFORE_CLICK_HANDLER:ec,SL_FIRST_PARTY_NA:Lb,SL_TRACK_IMPRESSION:Tb,WITH_NA_LINK_IMPRESSIONS:Sb,SL_REPLACE_TIMEOUT:yb,SL_AFFILIATE_UNKNOWN_LINKS:Wa,SL_TARGET:ba,AJAX_SUPPORT:Ed,UNLINKED_EXCLUDES:[],SL_FORECAST:ka,NO_RIGHT_CLICK:Fd,USE_MERCHANT_URL_EXTRACTION_RULES:fc,EXTRA_REDIR_PARAMS:Ga,CUSTOM_TRACKING_VAR:ja,FORCE_LOCATION:Fa,SITE_NAME:J,CUSTOM_WAYPOINT_DOMAIN:O,GOOGLE_TRACKING_ACTION_NAME:R,
NO_SKIM_DOMAINS:Xb,SW_HORIZONTAL_DISTANCE:Gd,SW_VERTICAL_DISTANCE:Hd,SL_PROFILING:!1,TRACK_COOKIE_SYNCS:Id,SW_LINK_COLOR:Jd,SW_LINK_WEIGHT:Kd,SW_LINK_DECORATION:Ld,SW_LINK_STYLE:Md,SW_LINK_TITLE:Nd,NO_SKIM_SELECTOR:$a,SL_CONSENT:!1,FORCE_CONSENT:Od,M101_TRACKING_ID:Pd,M101_CUSTOM_DOM_DETECTION:Qd,AE_CLICK_TRACKING:!1,INCENTIVE_ENABLED:!1,FORCE_PREVENTED_CLICKS_MONETIZATION:Rb,IS_MINIMALISTIC_JS:!1,LINK_SWAPPING_404:db,LINK_SWAPPING_OUT_OF_STOCK:!1,LINK_SWAPPING_PRODUCT_MATCH:eb,LINK_SWAPPING:Ea,LINK_SWAPPING_MERCHANT_NAME_DETECTION:gc},
k=function(){var a=I.referrer||document.referrer||"",b=Fa||l.location.href;var c="aspsession-id aspsessionid cftoken j-sessionid jsessid jsession_id jsessionid phpsessid phpsession-id phpsessionid seskey sessid session-id session-key session_id sessionid sessionkey uniqueid utm_campaign utm_medium utm_source utm_term".split(" ");for(var d=0;d<c.length;d++){var e=c[d];var h=b.split("?");if(2<=h.length){b=h.shift();h=h.join("?");e=encodeURIComponent(e)+"=";h=h.split(/[&;]/gi);for(var f=h.length-1;0<=
f;f--)Ka(h[f],e)&&h.splice(f,1);b=b+"?"+h.join("&")}}"?"===b[b.length-1]&&(b=b.substr(0,b.length-1));c=b;d=wd.getItem("skimCONSENT");b=navigator.userAgent.toLowerCase();b=/(webkit)[ /]([\w.]+)/.exec(b)||/(opera)(?:.*version)?[ /]([\w.]+)/.exec(b)||/(msie) ([\w.]+)/.exec(b)||0>b.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(b)||[];b={browser:b[1]||"",version:parseFloat(b[2])||0};return{cookieSyncString:"",lastBeaconTimestamp:null,cookie:"",country:"",locale:"",consent:d,detect:b,isAdblockUser:!1,
pageLocation:c,referrer:a,timezone:lb(),uuid:Ia(),skimwordsEnabled:cc,skimlinksEnabled:bc,unlinkedEnabled:dc}}(),n=function(){var a=document.getElementsByTagName("html")?document.getElementsByTagName("html")[0]:null,b=Fa?w(Fa,!1):l.location.hostname;return{aff_domains:{},beacon:[],domain_data:{domains:[]},exclude:cb,exclude_lookup:null,excluded_classes:["noskimlinks","noskim"].concat(bb),has_been_called:!1,hostname:b,html_root:a,include:xa,include_lookup:null,links:[],links_tracked:!1,target:null,
waypointDomain:O?"http://"+O:"https://"+Qa}}();var hc=function(a,b,c){if(0===b)return c;try{return a()}catch(d){return hc(a,b-1,c)}};get_real_link=function(a){if(null==a)return null;for(;"A"!==a.nodeName.toUpperCase();)if(a=hc(function(){return a.parentNode},3,null),null==a)return null;return a};var C,Pa={get:function(a,b,c,d){d=u({onError:ua},d,{method:"GET"});La(a,b,B(c),d)},post:function(a,b,c,d){d=u({onError:ua},d,{method:"POST"});La(a,b,B(c),d)}},Rd={waypointDomain:O||Qa},Da=function(){function a(a,
c){var b=this;void 0===c&&(c=Rd);f(this,"waypointDomain",void 0);f(this,"waypointParams",void 0);f(this,"updateWaypointParams",function(a){if(G(a,"url")&&z(a.url))throw Error("[WaypointUrlObject][updateWaypointParams] 'url' param can not be null nor undefined");b.waypointParams=wa({},b.waypointParams,{},a);b.cleanUpWaypointParamsAfterUpdate()});f(this,"getWaypointUrl",function(){var a=K(b.waypointParams);return""+b.getWaypointDomainProtocol()+b.waypointDomain+"/?"+a});f(this,"getTargetUrl",function(){return b.waypointParams.url});
f(this,"getTargetDomain",function(){return w(b.getTargetUrl())});f(this,"getWaypointDomainProtocol",function(){return b.waypointDomain===O?"http://":"https://"});f(this,"cleanUpWaypointParamsAfterUpdate",function(){t(b.waypointParams,function(a,c){z(a)&&delete b.waypointParams[c]});b.waypointParams=wa({},b.getDefaultWaypointParams(),{},b.waypointParams)});if(null==a||!a.url)throw Error("[WaypointUrlObject][constructor] 'url' is mandatory");this.waypointDomain=c.waypointDomain;this.updateWaypointParams(a)}
a.prototype.getDefaultWaypointParams=function(){var a={id:Ha,sref:l.location.href,xs:1};k.cookie&&(a.xguid=k.cookie);return a};a.createFromUrl=function(b){var c=w(b);if(!D(c))return null;try{var d=qb(b);return d.url?new a(d,{waypointDomain:c}):null}catch(e){return null}};return a}();"undefined"!==typeof window.Map&&(Q.Cache=Map);var Sd=["noskim","norewrite"],Td=["noskimlinks","noskim"].concat(["taboola","advert--taboola","trc_rbox","trc_related_container"]),Ud="*.criteo.com *.g.doubleclick.net *mjxads.internet.com *overture.com *pgpartner.co.uk *pgpartner.com *pricegrabber.co.uk *pricegrabber.com *youtube.com m.skimresources.com paid.outbrain.com track.celtra.com traffic.outbrain.com trc.taboola.com zergnet.com ad.doubleclick.net".split(" "),
Ec=["itunes.apple.com","itunes.com","phobos.apple.com"],Hc=Q(function(){var a=[].concat(cb,Ud);J&&a.push(J);return a}),Gc=Q(function(){return Td.concat(bb).map(function(a){return"."+a})}),Fc=Q(function(){return Sd.map(function(a){return"a[rel~='"+a+"']"})}),p;(function(a){a.AFFILIATE="AFFILIATE";a.PRE_AFFILIATED="PRE_AFFILIATED";a.UNKNOWN="UNKNOWN";a.TRACK="TRACK";a.IGNORE="IGNORE"})(p||(p={}));var Mb="__skimlinks__";var nc=function(a){a=X(a);if(fc){var b=w(a);if(b in Va)return b="[&?]"+Va[b].name+
"=(http[^&]+)",b=new RegExp(b),decodeURIComponent(null!=a?a.match(b).pop():void 0)||a}return a};var ic;(function(a){a.STARTING="STARTING";a.CANCELLED="CANCELLED";a.PENDING_API="PENDING_API";a.API_ERROR="API_ERROR";a.NO_OFFERS="NO_OFFERS";a.PENDING_MODULE="PENDING_MODULE";a.READY="READY"})(ic||(ic={}));var x={topics:{},on:function(a,b,c){M(this.topics[a])||(this.topics[a]=[]);var d;c&&(d=function(a){Nc(a,c)&&b(a)});this.topics[a].push(d||b)},publish:function(a,b){t(this.topics[a]||[],function(a){q(a)&&
a(b)})}},E=function(){function a(){var a=this;f(this,"ready",void 0);f(this,"pendingCallbacks",void 0);f(this,"subReadyStateList",void 0);f(this,"isReady",function(){return a.dependsOnSubReadyState()?Qc(a.subReadyStateList,function(a){return a.isReady()}):a.ready});f(this,"setReady",function(){a.dependsOnSubReadyState()||a.ready||(a.ready=!0,a.callPendingCallbacks())});f(this,"waitFor",function(b){b=Y(b,function(a){return!!a});a.subReadyStateList=a.subReadyStateList.concat(b);a.isReady()?a.callPendingCallbacks():
b.forEach(function(b){b.whenReady(a.whenSubReadyStateIsReady)})});f(this,"whenSubReadyStateIsReady",function(){a.isReady()&&a.callPendingCallbacks()});this.ready=!1;this.pendingCallbacks=[];this.subReadyStateList=[]}var b=a.prototype;b.whenReady=function(a){this.isReady()?a():this.pendingCallbacks.push(a)};b.dependsOnSubReadyState=function(){return 0!==this.subReadyStateList.length};b.callPendingCallbacks=function(){this.pendingCallbacks.forEach(function(a){setTimeout(a,0)});this.pendingCallbacks=
[]};return a}(),ia;(function(a){a.PRE_PAGE_LOAD="PRE_PAGE_LOAD";a.POST_PAGE_LOAD="POST_PAGE_LOAD";a.AUX="AUX"})(ia||(ia={}));var da=new (function(){function a(a,b){var c=this;f(this,"requestBeaconAPI",void 0);f(this,"beaconRequestHandler",void 0);f(this,"requestsHistory",void 0);f(this,"noRequestPendingReadyState",void 0);f(this,"beaconApiResponseReadyState",void 0);f(this,"postPageLoadCallReadyState",void 0);f(this,"beaconFullyReadyState",void 0);f(this,"whenNoRequestsPending",function(a){c.noRequestPendingReadyState.whenReady(a)});
f(this,"whenBeaconApiRequestCompleted",function(a){c.beaconApiResponseReadyState.whenReady(a)});f(this,"whenPostPageLoadBeaconCallCompleted",function(a){c.postPageLoadCallReadyState.whenReady(a)});f(this,"whenBeaconFullyReady",function(a){c.beaconFullyReadyState.whenReady(a)});f(this,"sendBeaconRequest",function(a,b){var d=0===a.length,e={readyState:new E,requestedDomains:a,response:null,beaconCallType:b};c.hasFetchedAtLeastOnce()&&d?(c.requestsHistory.push(e),e.readyState.setReady()):c.requestBeaconAPI(a,
b,function(b){b=u({requestedDomains:a},b);c.beaconRequestHandler(b);e.response=b;e.readyState.setReady()});c.updateRequestsHistory(e);e.readyState.whenReady(function(){e.response&&x.publish("EVENTS__BEACON__REQUEST_COMPLETED",e);c.resolveReadyStatesOnRequestCompleted(e)});return e});this.requestBeaconAPI=a;this.beaconRequestHandler=b;this.requestsHistory=[];this.noRequestPendingReadyState=new E;this.noRequestPendingReadyState.setReady();this.beaconApiResponseReadyState=new E;this.postPageLoadCallReadyState=
new E;this.beaconFullyReadyState=Rc(this.beaconApiResponseReadyState,this.postPageLoadCallReadyState)}var b=a.prototype;b.updateRequestsHistory=function(a){this.requestsHistory.push(a);this.noRequestPendingReadyState.waitFor([a.readyState])};b.resolveReadyStatesOnRequestCompleted=function(a){a.response&&!this.beaconApiResponseReadyState.isReady()&&this.beaconApiResponseReadyState.setReady();a.beaconCallType===ia.POST_PAGE_LOAD&&this.postPageLoadCallReadyState.setReady()};b.hasFetchedAtLeastOnce=function(){return 0!==
this.requestsHistory.length};return a}())(function(a,b,c){a=JSON.stringify({pubcode:Ha,page:l.location.href,domains:a,link_swapping:Ea});a={headers:{"Content-type":"application/x-www-form-urlencoded"},data:K({data:a}),withCredentials:!0};var d=ma();"production"!==ud&&(d._=b);Pa.post(""+sd,d,c,a)},function(a){var b={};a.country&&(b.country=a.country.toUpperCase());a.country_state&&(b.countryState=a.country_state);a.guid&&""===k.cookie&&(b.cookie=a.guid);sa(a.consent)&&(b.consent=a.consent);a.csp&&
(b.cookieSyncString=a.csp);a.ts&&(b.lastBeaconTimestamp=a.ts);u(k,b);Pc(a.requestedDomains,a.merchant_domains)}),T;(T||(T={})).ANCHOR_CLICK_INTERCEPTOR="ANCHOR_CLICK_INTERCEPTOR";var Pb={},S;(function(a){a.LEFT_CLICK="LEFT_CLICK";a.MIDDLE_CLICK="MIDDLE_CLICK";a.OTHER_CLICK="OTHER_CLICK"})(S||(S={}));var ca;(function(a){a[a.LINK_SWAPPING=0]="LINK_SWAPPING";a[a.CONSENT=1]="CONSENT";a[a.INCENTIVE=2]="INCENTIVE";a[a.SKIMLINKS=3]="SKIMLINKS"})(ca||(ca={}));var r={campaign_ids:[],loading_started:(new Date).getTime(),
linksImpressions:{skimlinks:{count:0,urls:{}},skimwords:{count:0,urls:{}},unlinked:{count:0,urls:{}}},awaitedModules:[]},Zc=["skimlinks_included_ids","skimlinks_byrel","skimlinks_exrel","skimlinks_included_classes"],jc=function(){function a(){f(this,"SERVICES",a.SERVICES);f(this,"getService",Xa);f(this,"trackEvent",Nb);x.on("skim_js_init",this.onInit.bind(this));x.on("skim_js_start",this.onStart.bind(this));da.whenBeaconFullyReady(this.whenBeaconFullyReady.bind(this))}var b=a.prototype;b.onInit=function(){};
b.onStart=function(){};b.whenBeaconFullyReady=function(){};b.publishEvent=function(a,b){x.publish(a,b)};b.onEvent=function(a,b){x.on(a,b)};b.registerClickInterceptor=function(a,b){Xa(T.ANCHOR_CLICK_INTERCEPTOR).registerInterceptor(a,b)};return a}();f(jc,"SERVICES",T);var kc=new E,Vd=function(a){function b(){var b=arguments.length;for(var c=Array(b),h=0;h<b;h++)c[h]=arguments[h];b=a.call.apply(a,[this].concat(c))||this;f(P(b),"excludedDomains",void 0);f(P(b),"linkSwappingDomains",[]);f(P(b),"otherMerchantDomains",
[]);f(P(b),"swappedAnchorsInfo",[]);f(P(b),"nonSwappedAnchorsInfo",[]);f(P(b),"onAnchorClick",function(a){var b=a.anchor.getAttribute("data-skimlinks-link-swapping-match-id");if(!b)return!1;a.setAnchorClickInterceptorTarget(ca.SKIMLINKS);a.setSourceApp(15);a.setLinkSwappingMatchId(b);return!1});return b}Ac(b,a);var c=b.prototype;c.onInit=function(){this.excludedDomains=g("skimlinks_excluded_link_swapping_domains",[]);this.onEvent("EVENTS__BEACON__REQUEST_COMPLETED",this.onBeaconRequestCompleted.bind(this))};
c.onStart=function(){this.registerClickInterceptor(this.onAnchorClick,ca.LINK_SWAPPING)};c.onBeaconRequestCompleted=function(a){var b=this;a=a.response;a.link_swapping_domains.forEach(function(a){m(b.linkSwappingDomains,a)||b.linkSwappingDomains.push(a)});a.merchant_domains.forEach(function(a){m(b.linkSwappingDomains,a)||m(b.otherMerchantDomains,a)||b.otherMerchantDomains.push(a)})};c.whenBeaconFullyReady=function(){var a=this,b=this.getSwappableAnchors();if(b.length){var c=this.sendLinkSwappingApiRequest(b);
c.readyState.whenReady(function(){var d=c.response;d&&0!==Object.keys(d).length&&(a.registerLinkSwappingDomainsAsAffiliate(d),a.applyLinkSwapping(b,d),a.sendLinkSwappingTracking(),a.sendLinkNonSwappedTracking());a.onLinkSwappingProcessDone()})}else this.onLinkSwappingProcessDone()};c.registerLinkSwappingDomainsAsAffiliate=function(a){t(a,function(a){t(a,function(a){a=a.matching_domain;!1!==n.aff_domains[a]&&(n.aff_domains[a]=!0)})})};c.getSwappableAnchors=function(){var a=this,b=Aa();return Y(b,function(b){if("false"===
(null==b?void 0:b.getAttribute("data-skimlinks-link-swapping")))return!1;var c=w(b.href);if(D(c)){var d=Da.createFromUrl(b.href);d&&(c=d.getTargetDomain())}return m(a.excludedDomains,c)||!m(a.linkSwappingDomains,c)&&!m(a.otherMerchantDomains,c)||Ta(b)?!1:!0})};c.sendLinkSwappingApiRequest=function(a){a=Ob(a.map(Ub));var b={readyState:new E,response:null};cd(a,function(a){b.response=a;b.readyState.setReady()});return b};c.applyLinkSwapping=function(a,b){var c=this;t(a,function(a){var d=Ub(a),e=c.getBestLinkSwappingMatch(b[d]);
d=c.isBlockedByMerchantNameOnPage(e,d);e&&!d?c.swapAnchorLink(a,e):d&&c.nonSwappedAnchorsInfo.push({originalHref:a.href,anchor:a,match:e,reason:"merchant_name_on_page"})})};c.getBestLinkSwappingMatch=function(a){return a?a.filter(function(a){return"404"===a.reason&&db||"product_match"===a.reason&&eb})[0]:null};c.isBlockedByMerchantNameOnPage=function(a,b){return gc&&a&&w(b)!==a.matching_domain?Sa(a.original_merchant_names,function(a){var b;return-1!==(null==(b=document.body)?void 0:b.innerText.toLowerCase().indexOf(a.toLowerCase()))}):
!1};c.swapAnchorLink=function(a,b){var c=a.href;a.setAttribute("data-skimlinks-link-swapping-original",c);a.setAttribute("data-skimlinks-link-swapping-match-id",b.id.toString());if(Fb(c)){var d=Da.createFromUrl(a.href);d.updateWaypointParams({url:encodeURIComponent(b.matching_link),xs:15,ls:b.id});a.href=d.getWaypointUrl()}else a.href=b.matching_link;this.swappedAnchorsInfo.push({originalHref:c,anchor:a,match:b})};c.sendLinkSwappingTracking=function(){var a=this.swappedAnchorsInfo.map(function(a){return{match:a.match,
originalHref:a.originalHref}});this.trackEvent("link_swapping__swapped_links",{number_of_links_swapped:this.swappedAnchorsInfo.length,swappedAnchorsInfo:JSON.stringify(a)})};c.sendLinkNonSwappedTracking=function(){var a=this.nonSwappedAnchorsInfo.map(function(a){return{match:a.match,originalHref:a.originalHref,reason:a.reason}});0<this.nonSwappedAnchorsInfo.length&&this.trackEvent("link_swapping__not_swapped",{number_of_links_non_swapped:this.nonSwappedAnchorsInfo.length,nonSwappedAnchorsInfo:JSON.stringify(a)})};
c.onLinkSwappingProcessDone=function(){kc.isReady()||kc.setReady()};return b}(jc),Za=!1,U=!1,ea=null,fa=null,qd={detect:function(a){a:{try{var b=navigator.userAgent.toLowerCase();if(-1===b.indexOf("firefox")&&-1===b.indexOf("chrome")){U=!0;Za=!1;break a}}catch(c){}b=""+11*Math.random();ea=new Image;ea.onload=Wb;ea.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"1").replace(/\*/,b);fa=new Image;fa.onload=Wb;fa.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"2").replace(/\*/,b)}Vb(a,
250)}};new E;var hd={},lc=sb([!!ec&&"mouseup","click"]),Wd=["auxclick","contextmenu","touchstart"],Xd=function(){function a(a,b){f(this,"type",void 0);f(this,"anchor",void 0);f(this,"affiliationType",void 0);f(this,"nativeEvent",void 0);f(this,"clientClickId",void 0);f(this,"targetedInterceptor",void 0);var c=Ic(a);this.type=this.getInternalClickType(b);this.anchor=a;this.affiliationType=c;this.nativeEvent=b;this.clientClickId=Ia();this.targetedInterceptor=null}var b=a.prototype;b.setAnchorClickInterceptorTarget=
function(a){this.targetedInterceptor=a};b.setSourceApp=function(a){var b=this.anchor;A(b).sourceApp=a;ya(b)};b.setLinkSwappingMatchId=function(a){var b=this.anchor;A(b).linkSwappingMatchId=a;ya(b)};b.getInternalClickType=function(a){return m(lc,a.type)&&0===a.button?S.LEFT_CLICK:"auxclick"!==a.type&&"click"!==a.type||1!==a.button?S.OTHER_CLICK:S.MIDDLE_CLICK};return a}(),md=function(){function a(){var a=this;f(this,"interceptors",void 0);f(this,"onClick",function(b,c){var d=hb(b);d&&(d.skimlinksOriginalHref&&
d.skimlinksRestoreSwappedLink(),d=new Xd(d,b),a.dispatchAnchorClick(d,c))});f(this,"registerInterceptor",function(b,c){if(!q(b))throw Error("InterceptorHandler should be a function");if(z(c))throw Error("Missing priority for click interceptor");a.interceptors.push({handler:b,priority:c});a.interceptors.sort(function(a,b){return a.priority-b.priority})});f(this,"triggerLeftClickFromMouseEvent",function(b,c){var d=a.findInterceptorsWithPriority(c);if(z(c))a.onClick(b);else if(d.length)a.onClick(b,d)});
this.interceptors=[];this.initGlobalClickHandler()}var b=a.prototype;b.initGlobalClickHandler=function(){Yb(I,lc,this.onClick,!0);Yb(I,Wd,this.onClick,!0)};b.dispatchAnchorClick=function(a,b){var c=this;(b||this.interceptors).some(function(b){var d=b.handler;return c.isTargetedInterceptor(b,a)?d(a):!1})};b.findInterceptorsWithPriority=function(a){return Y(this.interceptors,function(b){return b.priority===a})};b.isTargetedInterceptor=function(a,b){var c=b.targetedInterceptor===a.priority;return!b.targetedInterceptor||
c};return a}(),ha=B(function(){Zb(ia.POST_PAGE_LOAD);document.removeEventListener("DOMContentLoaded",ha);document.removeEventListener("load",ha)}),od={skimlinks:!1,skimwords:!1,unlinked:!1,audience:!1,GDPRConsent:!1,incentivePopup:!1};tb&&B(function(){x.on("skim_js_init",Vc);x.on("skim_js_init",ad);x.on("skim_js_start",bd);Ea&&new Vd;nd()})()})();
